SELECT * FROM sales_analysis.customer_behaviour_analysis;
USE sales_analysis;

SELECT * FROM CUSTOMER_BEHAVIOUR_ANALYSIS;

---------------------------------------------------------
-- BUSINEESS INSIGHT QUESTIONS
-------------------------------------------------------------------------------------
-- 1. WHICH CATEGORY GENERATES HIGHEST REVENUE?

SELECT 
    category, ROUND(SUM(purchase_amount), 2) AS REVENUE
FROM
    customer_behaviour_analysis
GROUP BY category
ORDER BY REVENUE DESC;

-- Business Problem: Company does not know which category contributes most in the revenue

-- Impact:- 
			-- Helps prioritize high performing categories
			-- Optimizes inventory planning
            -- Improves marketing ROI
---------------------------------------------------------------------------------------------
-- 2. Are discounts actually increasing purchase value?

SELECT 
    discount_applied,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_revenue
FROM
    customer_behaviour_analysis
GROUP BY discount_applied;

-- Business Probles:- Discount may decrease profit without inscreasing sales

-- Impact:- 
		-- Identify effectiveness of discounts
        -- Reduce unnecessary discount costs
        -- Improve profit margins
-----------------------------------------------------------------------------------------------

-- 3. What is total revenue generated by male and female cusotmers?

SELECT 
    gender, ROUND(SUM(purchase_amount), 2) AS REVENUE
FROM
    customer_behaviour_analysis
GROUP BY gender
ORDER BY REVENUE DESC;

-- Business Problem:- Lack of understanding of revenue contribution by gender segments.

-- Impact:- 
		-- Helps design targeted marketing campaigns
        -- Improves customer segmentation strategy
        -- Enhances personalization efforts
---------------------------------------------------------------------------------------------------------------

-- 4. Which customers used discounts but still spent more than the average purchase amount?

SELECT 
    customer_id, discount_applied, purchase_amount
FROM
    customer_behaviour_analysis
WHERE
    discount_applied = 'Yes'
        AND purchase_amount > (SELECT 
            AVG(purchase_amount)
        FROM
            customer_behaviour_analysis)
ORDER BY purchase_amount DESC
LIMIT 10;

-- Business Problem:- Company cannot identify high-spending customers who are also discount users.

-- Impact:- 
		-- Identify premium discount-sensitive customers
        -- Enables targeted discount campaigns
        -- Improves customer retension and revenue
-------------------------------------------------------------------------------------------------------------------

-- 5. Which are the top/bottom 5 products with highest avg review rating?

SELECT * FROM CUSTOMER_BEHAVIOUR_ANALYSIS;

SELECT 
    item_purchased, ROUND(AVG(review_rating), 2) review_rating
FROM
    CUSTOMER_BEHAVIOUR_ANALYSIS
GROUP BY item_purchased
ORDER BY review_rating DESC
LIMIT 5;

SELECT 
    item_purchased, ROUND(AVG(review_rating), 2) review_rating
FROM
    CUSTOMER_BEHAVIOUR_ANALYSIS
GROUP BY item_purchased
ORDER BY review_rating ASC
LIMIT 5;

-- Business Problem:- No visibiity into product performance based on customer satisfaction

-- IMPACT:-
		-- Promotes high performing products
        -- Improves low rated products
        -- Enhances customer experience
-------------------------------------------------------------------------------------------------

-- 6. Average purchase: Standard vs Express Shipping

SELECT * FROM customer_behaviour_analysis;

SELECT 
    shipping_type,
    COUNT(DISTINCT (customer_id)) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    ROUND(SUM(purchase_amount), 2) AS total_purchase_amount
FROM
    customer_behaviour_analysis
GROUP BY shipping_type
ORDER BY total_purchase_amount DESC;

-- Business Problem:- unclear if faster shipping leads to higher spending

-- Impact:- 
		-- Help optimize shipping pricing strategy
        -- Encourages premium shipping adoption
        -- Increases avg oshipping value 
--------------------------------------------------------------------------------------------------------------------

-- 7. Do subscribed customer spend more? Compare avg spend and total revenue between subscribers and non subscribers

SELECT * FROM customer_behaviour_analysis;

SELECT 
    subscription_status,
    COUNT(DISTINCT (customer_id)) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    ROUND(SUM(purchase_amount), 2) AS total_purchase_amount
FROM
    customer_behaviour_analysis
GROUP BY subscription_status
ORDER BY total_purchase_amount DESC;

-- Business Problem: The effectiveness of subscription programs is unknown

-- Impact:- 
		-- Validates subscription model performance
        -- Improves customer loyalty Program
        -- Increases customer lifetime value
---------------------------------------------------------------------------------------------------------------

-- 8. Top 5 products with highest discount usage

SELECT 
    item_purchased,
    COUNT(item_purchased) AS total_sold,
    COUNT(CASE
        WHEN discount_applied = 'Yes' THEN 1
    END) AS number_of_times_sold_when_discount_applied,
    COUNT(CASE
        WHEN discount_applied = 'Yes' THEN 1
    END) * 100 / COUNT(*) AS discount_percent
FROM
    customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY discount_percent DESC;


-- Business Problem :- Some products may be overly dependent on discounts.

-- Impact:- 
			-- Identifies discount-driven products
			-- Helps optimize pricing strategy
			-- Reduces profit margin loss
------------------------------------------------------------------------------------------------------------------------

-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase, 
-- and show the count of each segment.

SELECT * FROM customer_behaviour_analysis;

SELECT 
	CASE 
		WHEN previous_purchases= '0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15  THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END AS customer_segment,
COUNT(*) AS customer_count
FROM customer_behaviour_analysis
GROUP BY CASE 
		WHEN previous_purchases= '0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15  THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END;

-- Business Problem :- Lack of customer segmentation leads to generic strategies.


-- Impact:- 
			-- Enables personalized marketing
			-- Improves retention strategies
			-- Increases conversion rates

----------------------------------------------------------------------------------------------------------------------------

-- 10. What are the top 3 most purchased products within each category ?

SELECT * FROM customer_behaviour_analysis;

WITH CTE AS 
(
SELECT 
	category,
	item_purchased,
	COUNT(item_purchased) AS most_purchased,
	RANK() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
FROM customer_behaviour_analysis
GROUP BY category,item_purchased
)
SELECT * FROM CTE
WHERE RNK <=3;

-- Business Problem:- The company doesn’t know top-performing products within categories.

-- Impact
			-- Improves product placement & recommendations
			-- Helps inventory optimization
			-- Increases sales through best-sellers

----------------------------------------------------------------------------------------------------------------------------

-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

SELECT * FROM customer_behaviour_analysis;

SELECT
	CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END AS customer_type,
	subscription_status,
	COUNT(*) AS customer_count,
	COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE 
										WHEN previous_purchases > 5 THEN 'Repeat Buyers'
										ELSE 'Normal Buyers'
									END
									) AS percents

FROM customer_behaviour_analysis
GROUP BY CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END,subscription_status;

-- Business Problem :- Unclear relationship between loyalty and subscription.

-- Impact:- 
			-- Improves subscription targeting
			-- Increases conversion to paid programs
			-- increase customer retention strategy

----------------------------------------------------------------------------------------------------------------------------

-- 12. What is the revenue contribution of each age group ? 

SELECT * FROM customer_behaviour_analysis;

SELECT 
	CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END AS age_group,
	ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_behaviour_analysis
GROUP BY CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END
	ORDER BY total_revenue DESC;

-- Business Problem:- No visibility into which age group contributes most to revenue.

--  Impact:-
			-- Enables age-based targeting
			-- Enhances marketing efficiency